### ISSUE TITLE
基礎から学ぶRust版もほしい

### ISSUE THREAD

**Issue by dongri** [gridscaleinc/Learning-Java-Basic#1]
あけましておめでとうございますｗ

**Comment by domanthan** [comment]
誰が学びたい？

**Comment by domanthan** [comment]
こんなどころで新年あいさつするのがハッカーしかいないな。

**Comment by dongri** [comment]
![fff](https://user-images.githubusercontent.com/878993/71801670-ebf6af80-309e-11ea-9ef3-6297894c5ed5.png)

**Comment by dongri** [comment]
すみません、勝手に消しました。やる気出た時に作りますw
